version: "3.9"

services:
  rag_mcp_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Google_Project
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./server:/app/server
      - ./streamlit_app:/app/streamlit_app
      - ./client:/app/client
#      - ./server/data:/app/server/data
    environment:
      DOCUMENT_PATH: /app/server/data
    restart: unless-stopped